### ISSUE TITLE
Nunjucks support

### ISSUE THREAD

**Issue by cizar** [tj/co-views#17]
It will be nice to have a new version of co-views/co-render that support the [Nunjucks](http://mozilla.github.io/nunjucks) engine. Since Consolidate.js 0.10.0 already supports it, I suppose is just a matter of change  dependencies, but I do not know the impact of this change.

**Comment by coderhaoxin** [comment]
1452ff718cff9ba556c6a7e72a3332a55fbcc6b3

co-views@0.3.0
